addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"        % "0.10.2")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.5.0")
addSbtPlugin("pl.project13.scala"        % "sbt-jmh"             % "0.4.4")
addSbtPlugin("com.timushev.sbt"          % "sbt-updates"         % "0.6.4")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.4.2")
