name: CI

on:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  scalafmt:
    timeout-minutes: 45
    runs-on: ubuntu-latest
    steps:
      - run: env
        shell: bash
      - uses: actions/checkout@v4.1.0
      - uses: coursier/cache-action@v6.4.3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.2'
          java-version: '17'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Java env
        shell: bash
        run: | # Copied from https://github.com/graalvm/setup-graalvm/#quickstart-template
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
      - name: Use CI sbt jvmopts
        shell: bash
        run: |
          mv .jvmopts-ci .jvmopts
          cat .jvmopts
      - name: scalafmt
        run: sbt 'scalafmtCheckAll' # https://scalameta.org/scalafmt/docs/installation.html#task-keys

  unit-tests:
    timeout-minutes: 45
    runs-on: ubuntu-latest
    steps:
      - run: env
        shell: bash
      - uses: actions/checkout@v4.1.0
      - uses: coursier/cache-action@v6.4.3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.2'
          java-version: '17'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Java env
        shell: bash
        run: | # Copied from https://github.com/graalvm/setup-graalvm/#quickstart-template
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
      - name: Use CI sbt jvmopts
        shell: bash
        run: |
          mv .jvmopts-ci .jvmopts
          cat .jvmopts

      - name: Run tests
        shell: bash
        run: sbt 'clean;test'
