# Extracting dependency graph from sbt with: https://github.com/marketplace/actions/sbt-dependency-submission
name: Update Dependency Graph
on:
  push:
    branches:
      - main
jobs:
  dependency-graph:
    timeout-minutes: 45
    name: Update Dependency Graph
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: scalacenter/sbt-dependency-submission@v2.1.2
